# Advent of Code challenge 2021

## Day 4: Giant Squid

### Part 1 - Play Bingo and Find Winning Board Grid

In [208]:
import dask.array as da
import dask.dataframe as dd
import numpy as np
import pandas as pd

In [6]:
test_input = """
7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
"""

In [33]:
def get_bingo_nums(puz_input):
    """Extract first line of puzzle input as bingo numbers to be 'called'"""
    bingo_num_list = puz_input.strip().split('\n')[0]
    return [int(bingo) for bingo in bingo_num_list.split(',')]

In [34]:
bingo_nums = get_bingo_nums(puz_input=test_input)
bingo_nums

[7,
 4,
 9,
 5,
 11,
 17,
 23,
 2,
 0,
 14,
 21,
 24,
 10,
 16,
 13,
 6,
 15,
 25,
 12,
 22,
 18,
 20,
 8,
 19,
 3,
 26,
 1]

In [334]:
def get_bingo_grids(puz_input):
    bingo_lines = puz_input.strip().split('\n')[2:]

    bingo_grids = []
    grid_list = []

    for line in bingo_lines:
        if line == '':
            bingo_grids.append(np.array(grid_list))
            grid_list = []
        else:
            single_space_line = line.strip().replace('  ', ' ')
            grid_list.append([int(val) for val in single_space_line.split(' ')])
    else:
        bingo_grids.append(np.array(grid_list))
    
    return da.from_array(bingo_grids, chunks = (1, 5, 5))

In [289]:
# def get_bingo_grids(puz_input):
#     bingo_lines = puz_input.strip().split('\n')[2:]

#     bingo_grids = []
#     grid_list = []
#     df_num = 0

#     for line in bingo_lines:
#         if line == '':
#             df = pd.DataFrame(grid_list)
#             df.insert(0, 'chunk', df_num)
#             df.set_index('chunk')
#             bingo_grids.append(df)
#             grid_list = []
#             df_num += 1
#         else:
#             single_space_line = line.strip().replace('  ', ' ')
#             grid_list.append([int(val) for val in single_space_line.split(' ')])
#     else:
#         df = pd.DataFrame(grid_list)
#         df.insert(0, 'chunk', df_num)
#         df.set_index('chunk')
#         bingo_grids.append(df)
            
#     return dd.from_pandas(pd.concat(bingo_grids).reset_index(drop=True), chunksize = 5)

In [480]:
bingo_grids = get_bingo_grids(puz_input=test_input)
bingo_grids

dask.array<array, shape=(3, 5, 5), dtype=int64, chunksize=(1, 5, 5), chunktype=numpy.ndarray>

In [336]:
test = bingo_grids.compute()
test

array([[[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]],

       [[ 3, 15,  0,  2, 22],
        [ 9, 18, 13, 17,  5],
        [19,  8,  7, 25, 23],
        [20, 11, 10, 24,  4],
        [14, 21, 16, 12,  6]],

       [[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]]])

In [337]:
def make_bingo_trackers(bingo_grids):
    num_bingo_grids = len(bingo_grids)
    np_arr = [np.array([[False] * 5] * 5)] * num_bingo_grids
    return da.from_array(np_arr, chunks = (1, 5, 5))

In [291]:
# def make_bingo_trackers(bingo_grids):
#     num_bingo_grids = int(len(bingo_grids) / 5)
#     df = pd.concat([pd.DataFrame([[False] * 5] * (5 * num_bingo_grids))])
#     chunk_series = [0] * 5 + [1] * 5 + [2] * 5
#     df.insert(0, 'chunk', chunk_series)
#     df.set_index('chunk')
#     return dd.from_pandas(df, chunksize = 5)

In [479]:
bingo_trackers = make_bingo_trackers(bingo_grids)
bingo_trackers

dask.array<array, shape=(3, 5, 5), dtype=bool, chunksize=(1, 5, 5), chunktype=numpy.ndarray>

In [475]:
bingo_trackers.compute()

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [459]:
# along columns
da.all(bingo_trackers, axis = 1).compute()

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [460]:
# across rows
da.all(bingo_trackers, axis = 2).compute() 

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [381]:
bingo_grids[da.all(bingo_trackers, axis = 2).any(axis = 1).compute()].compute()

array([[[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]]])

In [390]:
da.all(bingo_trackers, axis = 2).any(axis = 1).any().compute()

True

In [481]:
def get_winning_board(bingo_trackers):
    if da.all(bingo_trackers, axis = 1).any():
        return da.all(bingo_trackers, axis = 1).any(axis = 1)
        
    if da.all(bingo_trackers, axis = 2).any():
        return da.all(bingo_trackers, axis = 2).any(axis = 1)
            
    return da.array([False, False])

In [509]:
def call_bingo_nums(bingo_nums):
    for i, bingo_num in enumerate(bingo_nums):
        print(i, end=', ')
        bingo_trackers[da.isin(bingo_grids, bingo_num)] = True
        winning_board = get_winning_board(bingo_trackers)
        if winning_board.any():
            print("Found winning board.")
            bingo_grids[bingo_trackers] = 0
            return (bingo_num, bingo_grids[winning_board].compute())
    else:
        return (bingo_num, bingo_trackers.compute())

In [516]:
def solve(puz_input):
    win_bingo_num, winning_board = call_bingo_nums(bingo_nums)
    score_win_board = da.sum(winning_board, axis=1).sum().compute()
    print("\nscore", score_win_board)
    print("bingo number", win_bingo_num)
    print("final score", score_win_board * win_bingo_num)

In [513]:
# reset bingo_grids, bingo_trackers
bingo_nums = get_bingo_nums(puz_input = test_input)
bingo_grids = get_bingo_grids(puz_input = test_input)
bingo_trackers = make_bingo_trackers(bingo_grids)
solve(puz_input = test_input)

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, Found winning board.

score 188
bingo number 24
final score 4512


In [ ]:
# Run with final puzzle input
with open('adv_2021_d4_input.txt', 'r') as f:
    puz_input = f.read()
    bingo_nums = get_bingo_nums(puz_input = puz_input)
    bingo_grids = get_bingo_grids(puz_input = puz_input)
    bingo_trackers = make_bingo_trackers(bingo_grids)
    solve(puz_input = puz_input)

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 

### Part 2 - Keeping Rows with MCB and LCB

In [94]:
def find_mcb_pt2(x):
    """Find most common bit in column array."""
    if sum(x) / len(x) < 0.5:
        return 0
    else:
        return 1
    
    
def find_lcb_pt2(x):
    """Find least common bit in column array."""
    if sum(x) / len(x) < 0.5:
        return 1
    else:
        return 0
    
    
def to_decimal(row):
    """Most common bit = gamma, least common bit = epsilon."""
    return int(''.join(str(x) for x in row.to_numpy()[0]), 2)


def solve_pt2(x, func):
    num_cols = x.shape[1]
    x_copy = x.copy()
    results = []

    for col in range(num_cols):
        col_array = x_copy[col]
        filter_bit = func(x=col_array)
        x_copy = x_copy[x_copy[col] == filter_bit]
        if len(x_copy) == 1:
            return to_decimal(row=x_copy)

Now our solve function has changed to accept a function (find_mcb or find_lcb) as input so that we can run it twice - once for each type (most common, least common bit). Once we've found the most/least common bit (our `filter_bit`) then we can filter our current dataframe copy by that bit value applied to the specific column we're testing.

In [95]:
def run_prog_pt2(puz_input):
    puz_input = pd.DataFrame([[int(bit) for bit in line] for line in puz_input.strip().split('\n')])
    oxygen_gen_rating = solve_pt2(puz_input, func=find_mcb_pt2)
    c02_scrub_rating = solve_pt2(puz_input, func=find_lcb_pt2)
    print(f"Oxygen Gen: {oxygen_gen_rating} | C02 Scrub: {c02_scrub_rating} | Final Answer: {oxygen_gen_rating * c02_scrub_rating}") 

In [96]:
# Test with given example
run_prog_pt2(puz_input=test_input)

Oxygen Gen: 23 | C02 Scrub: 10 | Final Answer: 230


In [97]:
# Run with final puzzle input
with open('adv_2021_d3_input.txt', 'r') as f:
    run_prog_pt2(puz_input=f.read())

Oxygen Gen: 1177 | C02 Scrub: 4070 | Final Answer: 4790390
